spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/boondi_test}
  flyway:
    clean-on-validation-error: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
